package model

import (
	"errors"
	"strings"
	"time"
)

// MappingStatus controls whether a DeviceMapping is eligible for use.
// Disabled mappings are retained for audit purposes but rejected at query time.
type MappingStatus string

const (
	MappingStatusActive   MappingStatus = "active"
	MappingStatusDisabled MappingStatus = "disabled"
)

// DeviceMapping is the core gateway aggregate: it binds an external system's
// device identifier to the internal CUCode used by the telemetry service.
//
// ExternalSystem + ExternalID uniquely identify the device from the EMS side.
// CUCode is the key used by vpp-telemetry (IngestTelemetry, GetSnapshot, etc.).
//
// One DeviceMapping per external device; one CUCode may appear in multiple
// mappings if the same CU is reachable from more than one external system.
type DeviceMapping struct {
	ID             string
	TenantID       string
	ExternalSystem string // e.g. "ems-sg", "iot-platform-a"
	ExternalID     string // device identifier assigned by the external system
	CUCode         string // internal CU identifier understood by vpp-telemetry
	Status         MappingStatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// NewDeviceMapping constructs a validated DeviceMapping with status=active.
// id should be a UUID v7 generated by the application layer (platform/idgen).
func NewDeviceMapping(id, tenantID, externalSystem, externalID, cuCode string) (*DeviceMapping, error) {
	m := &DeviceMapping{
		ID:             id,
		TenantID:       tenantID,
		ExternalSystem: externalSystem,
		ExternalID:     externalID,
		CUCode:         cuCode,
		Status:         MappingStatusActive,
	}
	if err := m.Validate(); err != nil {
		return nil, err
	}
	return m, nil
}

func (m *DeviceMapping) Validate() error {
	if strings.TrimSpace(m.ID) == "" {
		return errors.New("domain: mapping id is required")
	}
	if strings.TrimSpace(m.TenantID) == "" {
		return errors.New("domain: tenant_id is required")
	}
	if strings.TrimSpace(m.ExternalSystem) == "" {
		return errors.New("domain: external_system is required")
	}
	if strings.TrimSpace(m.ExternalID) == "" {
		return errors.New("domain: external_id is required")
	}
	if strings.TrimSpace(m.CUCode) == "" {
		return errors.New("domain: cu_code is required")
	}
	return nil
}

// IsActive reports whether this mapping is eligible for telemetry translation
// and command routing. Disabled mappings are silently rejected by the application layer.
func (m *DeviceMapping) IsActive() bool {
	return m.Status == MappingStatusActive
}

// Disable sets the mapping status to disabled and updates the timestamp.
// A disabled mapping is not deleted; it remains visible in the management API
// and can be re-enabled if needed (e.g. after a CU is restored in resource service).
func (m *DeviceMapping) Disable() {
	m.Status = MappingStatusDisabled
	m.UpdatedAt = time.Now()
}
