syntax = "proto3";

package resourcepb;

option go_package = "github.com/mushroomyuan/vpp-backend/api/resource/proto/gen;resourcepb";



message Location {
  double Latitude = 1;
  double Longitude = 2;
  string Address = 3;
}

enum SiteStatus {
  SITE_STATUS_UNKNOWN = 0;
  SITE_STATUS_UNDER_CONSTRUCTION = 1;
  SITE_STATUS_OPERATING = 2;
  SITE_STATUS_FAULT = 3;
  SITE_STATUS_OFFLINE = 4;
}

enum PointDataType {
  POINT_DATA_TYPE_UNSPECIFIED = 0;
  POINT_DATA_TYPE_FLOAT = 1;
  POINT_DATA_TYPE_INT = 2;
  POINT_DATA_TYPE_BOOL = 3;
  POINT_DATA_TYPE_ENUM = 4;
}

enum JobType {
  IMPORT_JOB_TYPE_UNSPECIFIED = 0;
  IMPORT_JOB_TYPE_ASSET = 1;
  IMPORT_JOB_TYPE_CU = 2;
  IMPORT_JOB_TYPE_POINT = 3;
}

enum JobStatus {
  IMPORT_JOB_STATUS_UNSPECIFIED = 0;
  IMPORT_JOB_STATUS_PENDING = 1;
  IMPORT_JOB_STATUS_RUNNING = 2;
  IMPORT_JOB_STATUS_SUCCESS = 3;
  IMPORT_JOB_STATUS_FAILED = 4;
}

enum ResourceLifecycleStatus {
  RESOURCE_LIFECYCLE_STATUS_UNSPECIFIED = 0;
  RESOURCE_LIFECYCLE_STATUS_ACTIVE = 1;
  RESOURCE_LIFECYCLE_STATUS_DISABLED = 2;
  RESOURCE_LIFECYCLE_STATUS_DECOMMISSIONED = 3;
}

