syntax = "proto3";

package resourcepb;

option go_package = "github.com/mushroomyuan/vpp-backend/api/resource/proto/gen;resourcepb";

import "google/protobuf/struct.proto";
import "modules/error.proto";

message Resource {
  string ID = 1;
  string TenantID = 2;
  string SiteID = 3;
  string Name = 4;
  string Type = 5;
  double Capacity = 6;
  string Manufacturer = 7;
  string Model = 8;
  google.protobuf.Struct Metadata = 9;
}

message CreateResourceRequest {
  string TenantID = 1;
  string SiteID = 2;
  string Name = 3;
  string Type = 4;
  double Capacity = 5;
  string Manufacturer = 6;
  string Model = 7;
  google.protobuf.Struct Metadata = 8;
}

message CreateResourceResponse {
  string ResourceID = 1;
}

message UpdateResourceRequest {
  string TenantID = 1;
  string ID = 2;
  string Name = 3;
  string Type = 4;
  double Capacity = 5;
  string Manufacturer = 6;
  string Model = 7;
  google.protobuf.Struct Metadata = 8;
}

message DeleteResourceRequest {
  string TenantID = 1;
  string ID = 2;
}

message GetResourceRequest {
  string TenantID = 1;
  string ID = 2;
}

message ListResourcesRequest {
  string TenantID = 1;
  string SiteID = 2;
  repeated string IDs = 3;
  repeated string Types = 4;
  string NameLike = 5;
  int32 Offset = 6;
  int32 Limit = 7;
}

message ListResourcesResponse {
  repeated Resource Resources = 1;
}

message ResourceItem {
  string Name = 1;
  string Type = 2;
  double Capacity = 3;
  string Manufacturer = 4;
  string Model = 5;
  google.protobuf.Struct Metadata = 6;
}



message BatchCreateResourcesRequest {
  string TenantID = 1;
  string SiteID = 2;
  repeated ResourceItem Items = 3;
  int32 BatchSize = 4;
}

message BatchCreateResourcesResponse {
  repeated string ResourceIDs = 1;
  repeated BatchItemError FailedItems = 2;
  int32 TotalCount = 3;
  int32 SuccessCount = 4;
}
