apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-config
data:
  DISPATCH_CONSUL_ADDR: host.docker.internal:8500
  DISPATCH_AUTH_AUTHZ_CASDOOR_URL: http://host.docker.internal:8000
  DISPATCH_AUTH_AUTHZ_SNAPSHOT_PATH: /tmp/dispatch-authz-snapshot.json
  GATEWAY_GRPC_ADDR: gateway.vpp.svc.cluster.local:5005
  DATABASE_DBNAME: dispatch
