apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    app.kubernetes.io/name: dispatch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dispatch
  ports:
    - name: grpc
      port: 5006
      targetPort: grpc
